// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (title, artist_id, release_year, cover_art_path)
VALUES ($1, $2, $3, $4)
RETURNING id, title, artist_id, release_year, cover_art_path, created_at
`

type CreateAlbumParams struct {
	Title        string      `json:"title"`
	ArtistID     pgtype.UUID `json:"artist_id"`
	ReleaseYear  pgtype.Int4 `json:"release_year"`
	CoverArtPath string      `json:"cover_art_path"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.Title,
		arg.ArtistID,
		arg.ReleaseYear,
		arg.CoverArtPath,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.ReleaseYear,
		&i.CoverArtPath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM albums
WHERE id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlbum, id)
	return err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, title, artist_id, release_year, cover_art_path, created_at FROM albums
WHERE id = $1
`

func (q *Queries) GetAlbum(ctx context.Context, id pgtype.UUID) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.ReleaseYear,
		&i.CoverArtPath,
		&i.CreatedAt,
	)
	return i, err
}

const getAlbumByTitleAndArtist = `-- name: GetAlbumByTitleAndArtist :one
SELECT id, title, artist_id, release_year, cover_art_path, created_at FROM albums
WHERE title = $1 AND artist_id = $2
`

type GetAlbumByTitleAndArtistParams struct {
	Title    string      `json:"title"`
	ArtistID pgtype.UUID `json:"artist_id"`
}

func (q *Queries) GetAlbumByTitleAndArtist(ctx context.Context, arg GetAlbumByTitleAndArtistParams) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByTitleAndArtist, arg.Title, arg.ArtistID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.ReleaseYear,
		&i.CoverArtPath,
		&i.CreatedAt,
	)
	return i, err
}

const getAlbumWithStats = `-- name: GetAlbumWithStats :one
SELECT
    albums.id, albums.title, albums.artist_id, albums.release_year, albums.cover_art_path, albums.created_at,
    COALESCE(SUM(tracks.duration_seconds), 0)::int AS duration_seconds,
    COALESCE(SUM(tracks.play_count), 0)::int AS play_count,
    COUNT(tracks.id)::int AS song_count,
    COALESCE(MODE() WITHIN GROUP (ORDER BY tracks.genre), '')::text AS genre
FROM albums
LEFT JOIN tracks ON tracks.album_id = albums.id
WHERE albums.id = $1
GROUP BY albums.id
`

type GetAlbumWithStatsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	ArtistID        pgtype.UUID        `json:"artist_id"`
	ReleaseYear     pgtype.Int4        `json:"release_year"`
	CoverArtPath    string             `json:"cover_art_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	PlayCount       int32              `json:"play_count"`
	SongCount       int32              `json:"song_count"`
	Genre           string             `json:"genre"`
}

func (q *Queries) GetAlbumWithStats(ctx context.Context, id pgtype.UUID) (GetAlbumWithStatsRow, error) {
	row := q.db.QueryRow(ctx, getAlbumWithStats, id)
	var i GetAlbumWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.ReleaseYear,
		&i.CoverArtPath,
		&i.CreatedAt,
		&i.DurationSeconds,
		&i.PlayCount,
		&i.SongCount,
		&i.Genre,
	)
	return i, err
}

const listAlbumsAlphabetical = `-- name: ListAlbumsAlphabetical :many
SELECT
    albums.id, albums.title, albums.artist_id, albums.release_year, albums.cover_art_path, albums.created_at,
    COALESCE(SUM(tracks.duration_seconds), 0)::int AS duration_seconds,
    COALESCE(SUM(tracks.play_count), 0)::int AS play_count,
    COUNT(tracks.id)::int AS song_count,
    COALESCE(MODE() WITHIN GROUP (ORDER BY tracks.genre), '')::text AS genre
FROM albums
LEFT JOIN tracks ON tracks.album_id = albums.id
GROUP BY albums.id
ORDER BY albums.title
LIMIT $1 OFFSET $2
`

type ListAlbumsAlphabeticalParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAlbumsAlphabeticalRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	ArtistID        pgtype.UUID        `json:"artist_id"`
	ReleaseYear     pgtype.Int4        `json:"release_year"`
	CoverArtPath    string             `json:"cover_art_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	PlayCount       int32              `json:"play_count"`
	SongCount       int32              `json:"song_count"`
	Genre           string             `json:"genre"`
}

func (q *Queries) ListAlbumsAlphabetical(ctx context.Context, arg ListAlbumsAlphabeticalParams) ([]ListAlbumsAlphabeticalRow, error) {
	rows, err := q.db.Query(ctx, listAlbumsAlphabetical, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsAlphabeticalRow
	for rows.Next() {
		var i ListAlbumsAlphabeticalRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ReleaseYear,
			&i.CoverArtPath,
			&i.CreatedAt,
			&i.DurationSeconds,
			&i.PlayCount,
			&i.SongCount,
			&i.Genre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByArtist = `-- name: ListAlbumsByArtist :many
SELECT id, title, artist_id, release_year, cover_art_path, created_at FROM albums
WHERE artist_id = $1
ORDER BY release_year, title
`

func (q *Queries) ListAlbumsByArtist(ctx context.Context, artistID pgtype.UUID) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ReleaseYear,
			&i.CoverArtPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsNewest = `-- name: ListAlbumsNewest :many
SELECT
    albums.id, albums.title, albums.artist_id, albums.release_year, albums.cover_art_path, albums.created_at,
    COALESCE(SUM(tracks.duration_seconds), 0)::int AS duration_seconds,
    COALESCE(SUM(tracks.play_count), 0)::int AS play_count,
    COUNT(tracks.id)::int AS song_count,
    COALESCE(MODE() WITHIN GROUP (ORDER BY tracks.genre), '')::text AS genre
FROM albums
LEFT JOIN tracks ON tracks.album_id = albums.id
GROUP BY albums.id
ORDER BY albums.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAlbumsNewestParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAlbumsNewestRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	ArtistID        pgtype.UUID        `json:"artist_id"`
	ReleaseYear     pgtype.Int4        `json:"release_year"`
	CoverArtPath    string             `json:"cover_art_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	PlayCount       int32              `json:"play_count"`
	SongCount       int32              `json:"song_count"`
	Genre           string             `json:"genre"`
}

func (q *Queries) ListAlbumsNewest(ctx context.Context, arg ListAlbumsNewestParams) ([]ListAlbumsNewestRow, error) {
	rows, err := q.db.Query(ctx, listAlbumsNewest, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsNewestRow
	for rows.Next() {
		var i ListAlbumsNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ReleaseYear,
			&i.CoverArtPath,
			&i.CreatedAt,
			&i.DurationSeconds,
			&i.PlayCount,
			&i.SongCount,
			&i.Genre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAlbums = `-- name: SearchAlbums :many
SELECT id, title, artist_id, release_year, cover_art_path, created_at FROM albums
WHERE title ILIKE '%' || $1 || '%'
ORDER BY title
LIMIT $2
`

type SearchAlbumsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, searchAlbums, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ReleaseYear,
			&i.CoverArtPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbumCoverArt = `-- name: UpdateAlbumCoverArt :exec
UPDATE albums
SET cover_art_path = $2
WHERE id = $1
`

type UpdateAlbumCoverArtParams struct {
	ID           pgtype.UUID `json:"id"`
	CoverArtPath string      `json:"cover_art_path"`
}

func (q *Queries) UpdateAlbumCoverArt(ctx context.Context, arg UpdateAlbumCoverArtParams) error {
	_, err := q.db.Exec(ctx, updateAlbumCoverArt, arg.ID, arg.CoverArtPath)
	return err
}
