// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (name)
VALUES ($1)
RETURNING id, name, image_url
`

func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.ImageUrl)
	return i, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artists
WHERE id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const getArtist = `-- name: GetArtist :one
SELECT id, name, image_url FROM artists
WHERE id = $1
`

func (q *Queries) GetArtist(ctx context.Context, id pgtype.UUID) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.ImageUrl)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, name, image_url FROM artists
WHERE name = $1
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByName, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.ImageUrl)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT DISTINCT artists.id, artists.name, artists.image_url FROM artists
JOIN track_artists ON track_artists.artist_id = artists.id
ORDER BY name
`

func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArtists = `-- name: SearchArtists :many
SELECT DISTINCT artists.id, artists.name, artists.image_url FROM artists
JOIN track_artists ON track_artists.artist_id = artists.id
WHERE artists.name ILIKE '%' || $1 || '%'
ORDER BY name
LIMIT $2
`

type SearchArtistsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, searchArtists, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArtistImageURL = `-- name: UpdateArtistImageURL :exec
UPDATE artists
SET image_url = $2
WHERE id = $1
`

type UpdateArtistImageURLParams struct {
	ID       pgtype.UUID `json:"id"`
	ImageUrl string      `json:"image_url"`
}

func (q *Queries) UpdateArtistImageURL(ctx context.Context, arg UpdateArtistImageURLParams) error {
	_, err := q.db.Exec(ctx, updateArtistImageURL, arg.ID, arg.ImageUrl)
	return err
}
