// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	ArtistID     pgtype.UUID        `json:"artist_id"`
	ReleaseYear  pgtype.Int4        `json:"release_year"`
	CoverArtPath string             `json:"cover_art_path"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Artist struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type Playlist struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Public    bool               `json:"public"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PlaylistTrack struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	TrackID    pgtype.UUID `json:"track_id"`
	Position   int32       `json:"position"`
}

type Track struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	AlbumID           pgtype.UUID        `json:"album_id"`
	ArtistID          pgtype.UUID        `json:"artist_id"`
	Genre             string             `json:"genre"`
	TrackNumber       int32              `json:"track_number"`
	DiscNumber        int32              `json:"disc_number"`
	DurationSeconds   int32              `json:"duration_seconds"`
	Path              string             `json:"path"`
	Format            string             `json:"format"`
	ReplayGainTrackDb pgtype.Float8      `json:"replay_gain_track_db"`
	BitDepth          int32              `json:"bit_depth"`
	SampleRate        int32              `json:"sample_rate"`
	Channels          int32              `json:"channels"`
	PlayCount         int32              `json:"play_count"`
	LastPlayedAt      pgtype.Timestamptz `json:"last_played_at"`
	BitRate           int32              `json:"bit_rate"`
	SizeBytes         int64              `json:"size_bytes"`
}

type TrackArtist struct {
	TrackID  pgtype.UUID `json:"track_id"`
	ArtistID pgtype.UUID `json:"artist_id"`
	Position int32       `json:"position"`
}

type User struct {
	ID                        pgtype.UUID        `json:"id"`
	Username                  string             `json:"username"`
	PasswordEncrypted         []byte             `json:"password_encrypted"`
	IsAdmin                   bool               `json:"is_admin"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	PasswordSubsonicEncrypted []byte             `json:"password_subsonic_encrypted"`
}
