// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist_tracks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlaylistTrack = `-- name: AddPlaylistTrack :one
INSERT INTO playlist_tracks (playlist_id, track_id, position)
VALUES ($1, $2, $3)
RETURNING playlist_id, track_id, position
`

type AddPlaylistTrackParams struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	TrackID    pgtype.UUID `json:"track_id"`
	Position   int32       `json:"position"`
}

func (q *Queries) AddPlaylistTrack(ctx context.Context, arg AddPlaylistTrackParams) (PlaylistTrack, error) {
	row := q.db.QueryRow(ctx, addPlaylistTrack, arg.PlaylistID, arg.TrackID, arg.Position)
	var i PlaylistTrack
	err := row.Scan(&i.PlaylistID, &i.TrackID, &i.Position)
	return i, err
}

const clearPlaylistTracks = `-- name: ClearPlaylistTracks :exec
DELETE FROM playlist_tracks
WHERE playlist_id = $1
`

func (q *Queries) ClearPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearPlaylistTracks, playlistID)
	return err
}

const countPlaylistTracks = `-- name: CountPlaylistTracks :one
SELECT COUNT(*) FROM playlist_tracks
WHERE playlist_id = $1
`

func (q *Queries) CountPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaylistTracks, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPlaylistTracks = `-- name: ListPlaylistTracks :many
SELECT playlist_id, track_id, position FROM playlist_tracks
WHERE playlist_id = $1
ORDER BY position
`

func (q *Queries) ListPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) ([]PlaylistTrack, error) {
	rows, err := q.db.Query(ctx, listPlaylistTracks, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaylistTrack
	for rows.Next() {
		var i PlaylistTrack
		if err := rows.Scan(&i.PlaylistID, &i.TrackID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlaylistTrack = `-- name: RemovePlaylistTrack :exec
DELETE FROM playlist_tracks
WHERE playlist_id = $1 AND track_id = $2
`

type RemovePlaylistTrackParams struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	TrackID    pgtype.UUID `json:"track_id"`
}

func (q *Queries) RemovePlaylistTrack(ctx context.Context, arg RemovePlaylistTrackParams) error {
	_, err := q.db.Exec(ctx, removePlaylistTrack, arg.PlaylistID, arg.TrackID)
	return err
}

const removePlaylistTrackAtPosition = `-- name: RemovePlaylistTrackAtPosition :exec
DELETE FROM playlist_tracks
WHERE playlist_id = $1 AND position = $2
`

type RemovePlaylistTrackAtPositionParams struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	Position   int32       `json:"position"`
}

func (q *Queries) RemovePlaylistTrackAtPosition(ctx context.Context, arg RemovePlaylistTrackAtPositionParams) error {
	_, err := q.db.Exec(ctx, removePlaylistTrackAtPosition, arg.PlaylistID, arg.Position)
	return err
}

const shiftPlaylistTracksAfterPosition = `-- name: ShiftPlaylistTracksAfterPosition :exec
UPDATE playlist_tracks
SET position = position - 1
WHERE playlist_id = $1 AND position > $2
`

type ShiftPlaylistTracksAfterPositionParams struct {
	PlaylistID pgtype.UUID `json:"playlist_id"`
	Position   int32       `json:"position"`
}

func (q *Queries) ShiftPlaylistTracksAfterPosition(ctx context.Context, arg ShiftPlaylistTracksAfterPositionParams) error {
	_, err := q.db.Exec(ctx, shiftPlaylistTracksAfterPosition, arg.PlaylistID, arg.Position)
	return err
}
