// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (name, owner_id, public)
VALUES ($1, $2, $3)
RETURNING id, name, owner_id, public, created_at, updated_at
`

type CreatePlaylistParams struct {
	Name    string      `json:"name"`
	OwnerID pgtype.UUID `json:"owner_id"`
	Public  bool        `json:"public"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.Name, arg.OwnerID, arg.Public)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists
WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlaylist, id)
	return err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, name, owner_id, public, created_at, updated_at FROM playlists
WHERE id = $1
`

func (q *Queries) GetPlaylist(ctx context.Context, id pgtype.UUID) (Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlaylistsByOwner = `-- name: ListPlaylistsByOwner :many
SELECT
    playlists.id, playlists.name, playlists.owner_id, playlists.public, playlists.created_at, playlists.updated_at,
    COUNT(playlist_tracks.track_id)::int AS song_count,
    COALESCE(SUM(tracks.duration_seconds), 0)::int AS duration_seconds
FROM playlists
LEFT JOIN playlist_tracks ON playlist_tracks.playlist_id = playlists.id
LEFT JOIN tracks ON tracks.id = playlist_tracks.track_id
WHERE playlists.owner_id = $1
GROUP BY playlists.id
ORDER BY playlists.name
`

type ListPlaylistsByOwnerRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	OwnerID         pgtype.UUID        `json:"owner_id"`
	Public          bool               `json:"public"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SongCount       int32              `json:"song_count"`
	DurationSeconds int32              `json:"duration_seconds"`
}

func (q *Queries) ListPlaylistsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ListPlaylistsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistsByOwnerRow
	for rows.Next() {
		var i ListPlaylistsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Public,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SongCount,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists
SET name = $2, public = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, owner_id, public, created_at, updated_at
`

type UpdatePlaylistParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Public bool        `json:"public"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, updatePlaylist, arg.ID, arg.Name, arg.Public)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Public,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
