// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPlaylistTrack(ctx context.Context, arg AddPlaylistTrackParams) (PlaylistTrack, error)
	ClearPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) error
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreateArtist(ctx context.Context, name string) (Artist, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAlbum(ctx context.Context, id pgtype.UUID) error
	DeleteArtist(ctx context.Context, id pgtype.UUID) error
	DeletePlaylist(ctx context.Context, id pgtype.UUID) error
	DeleteTrack(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAlbum(ctx context.Context, id pgtype.UUID) (Album, error)
	GetAlbumByTitleAndArtist(ctx context.Context, arg GetAlbumByTitleAndArtistParams) (Album, error)
	GetArtist(ctx context.Context, id pgtype.UUID) (Artist, error)
	GetArtistByName(ctx context.Context, name string) (Artist, error)
	GetPlaylist(ctx context.Context, id pgtype.UUID) (Playlist, error)
	GetTrack(ctx context.Context, id pgtype.UUID) (Track, error)
	GetTrackByPath(ctx context.Context, path string) (Track, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAlbumsAlphabetical(ctx context.Context, arg ListAlbumsAlphabeticalParams) ([]Album, error)
	ListAlbumsByArtist(ctx context.Context, artistID pgtype.UUID) ([]Album, error)
	ListAlbumsNewest(ctx context.Context, arg ListAlbumsNewestParams) ([]Album, error)
	ListArtists(ctx context.Context) ([]Artist, error)
	ListGenres(ctx context.Context) ([]ListGenresRow, error)
	ListPlaylistTracks(ctx context.Context, playlistID pgtype.UUID) ([]PlaylistTrack, error)
	ListPlaylistsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Playlist, error)
	ListTracksByAlbum(ctx context.Context, albumID pgtype.UUID) ([]Track, error)
	ListTracksByArtist(ctx context.Context, artistID pgtype.UUID) ([]Track, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemovePlaylistTrack(ctx context.Context, arg RemovePlaylistTrackParams) error
	ScrobbleTrack(ctx context.Context, arg ScrobbleTrackParams) error
	SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]Album, error)
	SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]Artist, error)
	SearchTracks(ctx context.Context, arg SearchTracksParams) ([]Track, error)
	UpdateAlbumCoverArt(ctx context.Context, arg UpdateAlbumCoverArtParams) error
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error)
}

var _ Querier = (*Queries)(nil)
