// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: starred_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStarredAt = `-- name: GetStarredAt :one
SELECT starred_at FROM starred_items
WHERE user_id = $1 AND item_type = $2 AND item_id = $3
`

type GetStarredAtParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ItemType string      `json:"item_type"`
	ItemID   pgtype.UUID `json:"item_id"`
}

func (q *Queries) GetStarredAt(ctx context.Context, arg GetStarredAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getStarredAt, arg.UserID, arg.ItemType, arg.ItemID)
	var starred_at pgtype.Timestamptz
	err := row.Scan(&starred_at)
	return starred_at, err
}

const listStarredAlbums = `-- name: ListStarredAlbums :many
SELECT
    albums.id, albums.title, albums.artist_id, albums.release_year, albums.cover_art_path, albums.created_at,
    starred_items.starred_at,
    COALESCE(SUM(tracks.duration_seconds), 0)::int AS duration_seconds,
    COALESCE(SUM(tracks.play_count), 0)::int AS play_count,
    COUNT(tracks.id)::int AS song_count,
    COALESCE(MODE() WITHIN GROUP (ORDER BY tracks.genre), '')::text AS genre
FROM albums
JOIN starred_items ON starred_items.item_type = 'album' AND starred_items.item_id = albums.id
LEFT JOIN tracks ON tracks.album_id = albums.id
WHERE starred_items.user_id = $1
GROUP BY albums.id, starred_items.starred_at
ORDER BY starred_items.starred_at
`

type ListStarredAlbumsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Title           string             `json:"title"`
	ArtistID        pgtype.UUID        `json:"artist_id"`
	ReleaseYear     pgtype.Int4        `json:"release_year"`
	CoverArtPath    string             `json:"cover_art_path"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StarredAt       pgtype.Timestamptz `json:"starred_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	PlayCount       int32              `json:"play_count"`
	SongCount       int32              `json:"song_count"`
	Genre           string             `json:"genre"`
}

func (q *Queries) ListStarredAlbums(ctx context.Context, userID pgtype.UUID) ([]ListStarredAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listStarredAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarredAlbumsRow
	for rows.Next() {
		var i ListStarredAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.ReleaseYear,
			&i.CoverArtPath,
			&i.CreatedAt,
			&i.StarredAt,
			&i.DurationSeconds,
			&i.PlayCount,
			&i.SongCount,
			&i.Genre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredArtists = `-- name: ListStarredArtists :many
SELECT artists.id, artists.name, artists.image_url, starred_items.starred_at
FROM artists
JOIN starred_items ON starred_items.item_type = 'artist' AND starred_items.item_id = artists.id
WHERE starred_items.user_id = $1
ORDER BY starred_items.starred_at
`

type ListStarredArtistsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	ImageUrl  string             `json:"image_url"`
	StarredAt pgtype.Timestamptz `json:"starred_at"`
}

func (q *Queries) ListStarredArtists(ctx context.Context, userID pgtype.UUID) ([]ListStarredArtistsRow, error) {
	rows, err := q.db.Query(ctx, listStarredArtists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarredArtistsRow
	for rows.Next() {
		var i ListStarredArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.StarredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredItemIDsByType = `-- name: ListStarredItemIDsByType :many
SELECT item_id, starred_at FROM starred_items
WHERE user_id = $1 AND item_type = $2
`

type ListStarredItemIDsByTypeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ItemType string      `json:"item_type"`
}

type ListStarredItemIDsByTypeRow struct {
	ItemID    pgtype.UUID        `json:"item_id"`
	StarredAt pgtype.Timestamptz `json:"starred_at"`
}

func (q *Queries) ListStarredItemIDsByType(ctx context.Context, arg ListStarredItemIDsByTypeParams) ([]ListStarredItemIDsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listStarredItemIDsByType, arg.UserID, arg.ItemType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarredItemIDsByTypeRow
	for rows.Next() {
		var i ListStarredItemIDsByTypeRow
		if err := rows.Scan(&i.ItemID, &i.StarredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStarredTracks = `-- name: ListStarredTracks :many
SELECT tracks.id, tracks.title, tracks.album_id, tracks.artist_id, tracks.genre, tracks.track_number, tracks.disc_number, tracks.duration_seconds, tracks.path, tracks.format, tracks.replay_gain_track_db, tracks.bit_depth, tracks.sample_rate, tracks.channels, tracks.play_count, tracks.last_played_at, tracks.bit_rate, tracks.size_bytes, tracks.fingerprint, starred_items.starred_at
FROM tracks
JOIN starred_items ON starred_items.item_type = 'track' AND starred_items.item_id = tracks.id
WHERE starred_items.user_id = $1
ORDER BY starred_items.starred_at
`

type ListStarredTracksRow struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	AlbumID           pgtype.UUID        `json:"album_id"`
	ArtistID          pgtype.UUID        `json:"artist_id"`
	Genre             string             `json:"genre"`
	TrackNumber       int32              `json:"track_number"`
	DiscNumber        int32              `json:"disc_number"`
	DurationSeconds   int32              `json:"duration_seconds"`
	Path              string             `json:"path"`
	Format            string             `json:"format"`
	ReplayGainTrackDb pgtype.Float8      `json:"replay_gain_track_db"`
	BitDepth          int32              `json:"bit_depth"`
	SampleRate        int32              `json:"sample_rate"`
	Channels          int32              `json:"channels"`
	PlayCount         int32              `json:"play_count"`
	LastPlayedAt      pgtype.Timestamptz `json:"last_played_at"`
	BitRate           int32              `json:"bit_rate"`
	SizeBytes         int64              `json:"size_bytes"`
	Fingerprint       string             `json:"fingerprint"`
	StarredAt         pgtype.Timestamptz `json:"starred_at"`
}

func (q *Queries) ListStarredTracks(ctx context.Context, userID pgtype.UUID) ([]ListStarredTracksRow, error) {
	rows, err := q.db.Query(ctx, listStarredTracks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStarredTracksRow
	for rows.Next() {
		var i ListStarredTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.ArtistID,
			&i.Genre,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationSeconds,
			&i.Path,
			&i.Format,
			&i.ReplayGainTrackDb,
			&i.BitDepth,
			&i.SampleRate,
			&i.Channels,
			&i.PlayCount,
			&i.LastPlayedAt,
			&i.BitRate,
			&i.SizeBytes,
			&i.Fingerprint,
			&i.StarredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const starItem = `-- name: StarItem :exec
INSERT INTO starred_items (user_id, item_type, item_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, item_type, item_id) DO NOTHING
`

type StarItemParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ItemType string      `json:"item_type"`
	ItemID   pgtype.UUID `json:"item_id"`
}

func (q *Queries) StarItem(ctx context.Context, arg StarItemParams) error {
	_, err := q.db.Exec(ctx, starItem, arg.UserID, arg.ItemType, arg.ItemID)
	return err
}

const unstarItem = `-- name: UnstarItem :exec
DELETE FROM starred_items
WHERE user_id = $1 AND item_type = $2 AND item_id = $3
`

type UnstarItemParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ItemType string      `json:"item_type"`
	ItemID   pgtype.UUID `json:"item_id"`
}

func (q *Queries) UnstarItem(ctx context.Context, arg UnstarItemParams) error {
	_, err := q.db.Exec(ctx, unstarItem, arg.UserID, arg.ItemType, arg.ItemID)
	return err
}
