// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: track_artists.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrackArtist = `-- name: CreateTrackArtist :exec
INSERT INTO track_artists (track_id, artist_id, position)
VALUES ($1, $2, $3)
`

type CreateTrackArtistParams struct {
	TrackID  pgtype.UUID `json:"track_id"`
	ArtistID pgtype.UUID `json:"artist_id"`
	Position int32       `json:"position"`
}

func (q *Queries) CreateTrackArtist(ctx context.Context, arg CreateTrackArtistParams) error {
	_, err := q.db.Exec(ctx, createTrackArtist, arg.TrackID, arg.ArtistID, arg.Position)
	return err
}

const listArtistsByTrack = `-- name: ListArtistsByTrack :many
SELECT artists.id, artists.name
FROM artists
JOIN track_artists ON track_artists.artist_id = artists.id
WHERE track_artists.track_id = $1
ORDER BY track_artists.position
`

func (q *Queries) ListArtistsByTrack(ctx context.Context, trackID pgtype.UUID) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtistsByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByArtistIDIncludingFeatured = `-- name: ListTracksByArtistIDIncludingFeatured :many
SELECT DISTINCT tracks.id, tracks.title, tracks.album_id, tracks.artist_id, tracks.genre, tracks.track_number, tracks.disc_number, tracks.duration_seconds, tracks.path, tracks.format, tracks.replay_gain_track_db, tracks.bit_depth, tracks.sample_rate, tracks.channels, tracks.play_count, tracks.last_played_at, tracks.bit_rate, tracks.size_bytes
FROM tracks
JOIN track_artists ON track_artists.track_id = tracks.id
WHERE track_artists.artist_id = $1
ORDER BY tracks.title
`

func (q *Queries) ListTracksByArtistIDIncludingFeatured(ctx context.Context, artistID pgtype.UUID) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByArtistIDIncludingFeatured, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.ArtistID,
			&i.Genre,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationSeconds,
			&i.Path,
			&i.Format,
			&i.ReplayGainTrackDb,
			&i.BitDepth,
			&i.SampleRate,
			&i.Channels,
			&i.PlayCount,
			&i.LastPlayedAt,
			&i.BitRate,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
