// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (
    title, album_id, artist_id, genre, track_number, disc_number,
    duration_seconds, path, format, replay_gain_track_db,
    bit_depth, sample_rate, channels
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13
)
RETURNING id, title, album_id, artist_id, genre, track_number, disc_number, duration_seconds, path, format, replay_gain_track_db, bit_depth, sample_rate, channels
`

type CreateTrackParams struct {
	Title             string        `json:"title"`
	AlbumID           pgtype.UUID   `json:"album_id"`
	ArtistID          pgtype.UUID   `json:"artist_id"`
	Genre             string        `json:"genre"`
	TrackNumber       int32         `json:"track_number"`
	DiscNumber        int32         `json:"disc_number"`
	DurationSeconds   int32         `json:"duration_seconds"`
	Path              string        `json:"path"`
	Format            string        `json:"format"`
	ReplayGainTrackDb pgtype.Float8 `json:"replay_gain_track_db"`
	BitDepth          int32         `json:"bit_depth"`
	SampleRate        int32         `json:"sample_rate"`
	Channels          int32         `json:"channels"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.Title,
		arg.AlbumID,
		arg.ArtistID,
		arg.Genre,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.DurationSeconds,
		arg.Path,
		arg.Format,
		arg.ReplayGainTrackDb,
		arg.BitDepth,
		arg.SampleRate,
		arg.Channels,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.ArtistID,
		&i.Genre,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationSeconds,
		&i.Path,
		&i.Format,
		&i.ReplayGainTrackDb,
		&i.BitDepth,
		&i.SampleRate,
		&i.Channels,
	)
	return i, err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM tracks
WHERE id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrack, id)
	return err
}

const getTrack = `-- name: GetTrack :one
SELECT id, title, album_id, artist_id, genre, track_number, disc_number, duration_seconds, path, format, replay_gain_track_db, bit_depth, sample_rate, channels FROM tracks
WHERE id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id pgtype.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.ArtistID,
		&i.Genre,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationSeconds,
		&i.Path,
		&i.Format,
		&i.ReplayGainTrackDb,
		&i.BitDepth,
		&i.SampleRate,
		&i.Channels,
	)
	return i, err
}

const getTrackByPath = `-- name: GetTrackByPath :one
SELECT id, title, album_id, artist_id, genre, track_number, disc_number, duration_seconds, path, format, replay_gain_track_db, bit_depth, sample_rate, channels FROM tracks
WHERE path = $1
`

func (q *Queries) GetTrackByPath(ctx context.Context, path string) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByPath, path)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.ArtistID,
		&i.Genre,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DurationSeconds,
		&i.Path,
		&i.Format,
		&i.ReplayGainTrackDb,
		&i.BitDepth,
		&i.SampleRate,
		&i.Channels,
	)
	return i, err
}

const listGenres = `-- name: ListGenres :many
SELECT genre, COUNT(*) AS song_count, COUNT(DISTINCT album_id) AS album_count
FROM tracks
WHERE genre != ''
GROUP BY genre
ORDER BY genre
`

type ListGenresRow struct {
	Genre      string `json:"genre"`
	SongCount  int64  `json:"song_count"`
	AlbumCount int64  `json:"album_count"`
}

func (q *Queries) ListGenres(ctx context.Context) ([]ListGenresRow, error) {
	rows, err := q.db.Query(ctx, listGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenresRow
	for rows.Next() {
		var i ListGenresRow
		if err := rows.Scan(&i.Genre, &i.SongCount, &i.AlbumCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbum = `-- name: ListTracksByAlbum :many
SELECT id, title, album_id, artist_id, genre, track_number, disc_number, duration_seconds, path, format, replay_gain_track_db, bit_depth, sample_rate, channels FROM tracks
WHERE album_id = $1
ORDER BY disc_number, track_number
`

func (q *Queries) ListTracksByAlbum(ctx context.Context, albumID pgtype.UUID) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.ArtistID,
			&i.Genre,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationSeconds,
			&i.Path,
			&i.Format,
			&i.ReplayGainTrackDb,
			&i.BitDepth,
			&i.SampleRate,
			&i.Channels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByArtist = `-- name: ListTracksByArtist :many
SELECT id, title, album_id, artist_id, genre, track_number, disc_number, duration_seconds, path, format, replay_gain_track_db, bit_depth, sample_rate, channels FROM tracks
WHERE artist_id = $1
ORDER BY title
`

func (q *Queries) ListTracksByArtist(ctx context.Context, artistID pgtype.UUID) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.ArtistID,
			&i.Genre,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationSeconds,
			&i.Path,
			&i.Format,
			&i.ReplayGainTrackDb,
			&i.BitDepth,
			&i.SampleRate,
			&i.Channels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTracks = `-- name: SearchTracks :many
SELECT id, title, album_id, artist_id, genre, track_number, disc_number, duration_seconds, path, format, replay_gain_track_db, bit_depth, sample_rate, channels FROM tracks
WHERE title ILIKE '%' || $1 || '%'
ORDER BY title
LIMIT $2
`

type SearchTracksParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchTracks(ctx context.Context, arg SearchTracksParams) ([]Track, error) {
	rows, err := q.db.Query(ctx, searchTracks, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.ArtistID,
			&i.Genre,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DurationSeconds,
			&i.Path,
			&i.Format,
			&i.ReplayGainTrackDb,
			&i.BitDepth,
			&i.SampleRate,
			&i.Channels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
